"""
PromptGuard Agent — Runner

Haftalık çalışan orkestrasyon döngüsü:
  1. audit.jsonl'i analiz et (FP/FN tespiti)
  2. Dataset varsa precision/recall ölç
  3. Claude API ile pattern önerisi üret
  4. GitHub PR aç (insan onayı için)

Kullanım:
  python agent/runner.py --audit proxy/audit.jsonl
  python agent/runner.py --audit proxy/audit.jsonl --dataset data/hackaprompt.csv
  python agent/runner.py --dry-run   # PR açmadan raporu yazdır
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

from analyzer import analyze, AnalysisReport
from evaluator import evaluate, kpi_check, EvalResult, LabeledSample
from pattern_proposer import (
    propose_for_fn,
    propose_for_fp,
    proposals_to_markdown,
    Proposal,
)


# ─── GitHub PR ───────────────────────────────────────────────────────────────

def _gh_available() -> bool:
    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def open_pr(
    repo_root: Path,
    proposals: list[Proposal],
    report: AnalysisReport,
    eval_result: EvalResult | None,
) -> str | None:
    """
    Creates a branch, writes a proposals JSON, opens a GitHub PR.
    Returns the PR URL or None if gh CLI unavailable.
    """
    if not _gh_available():
        print("⚠️  gh CLI not found — skipping PR creation.")
        return None

    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M")
    branch = f"agent/pattern-proposals-{timestamp}"

    proposals_path = repo_root / "agent" / "pending_proposals.json"
    import json
    proposals_data = []
    for p in proposals:
        proposals_data.append(p.__dict__)
    proposals_path.write_text(json.dumps(proposals_data, indent=2))

    subprocess.run(["git", "-C", str(repo_root), "checkout", "-b", branch], check=True)
    subprocess.run(["git", "-C", str(repo_root), "add", str(proposals_path)], check=True)
    subprocess.run([
        "git", "-C", str(repo_root), "commit", "-m",
        f"agent: pattern proposals {timestamp}"
    ], check=True)
    subprocess.run([
        "git", "-C", str(repo_root), "push", "origin", branch
    ], check=True)

    body = _build_pr_body(proposals, report, eval_result)

    result = subprocess.run([
        "gh", "pr", "create",
        "--title", f"Agent: Pattern proposals {timestamp}",
        "--body", body,
        "--base", "main",
        "--head", branch,
    ], capture_output=True, text=True, cwd=str(repo_root))

    if result.returncode == 0:
        url = result.stdout.strip()
        print(f"✅ PR opened: {url}")
        return url

    print(f"❌ PR creation failed: {result.stderr}")
    return None


def _build_pr_body(
    proposals: list[Proposal],
    report: AnalysisReport,
    eval_result: EvalResult | None,
) -> str:
    parts = [
        "## PromptGuard Agent Report\n",
        "### Audit Analysis\n",
        f"```\n{report.summary}\n```\n",
    ]

    if eval_result:
        kpi = kpi_check(eval_result)
        parts += [
            "### KPI Evaluation\n",
            f"| Metric | Value | Target | Status |",
            f"|--------|-------|--------|--------|",
            f"| Precision | {eval_result.precision:.4f} | ≥0.80 | {'✅' if kpi['precision_ok'] else '❌'} |",
            f"| Recall    | {eval_result.recall:.4f}    | ≥0.70 | {'✅' if kpi['recall_ok'] else '❌'} |",
            f"| FP Rate   | {eval_result.fp_rate:.4f}   | ≤0.05 | {'✅' if kpi['fp_rate_ok'] else '❌'} |",
            f"| F1        | {eval_result.f1:.4f}        | -     | - |",
            "",
        ]

    parts += [
        "### Proposed Changes\n",
        proposals_to_markdown(proposals),
        "\n---",
        "*Generated by PromptGuard Agent. Review before merging.*",
    ]

    return "\n".join(parts)


# ─── Main ────────────────────────────────────────────────────────────────────

def run(
    audit_path: str,
    dataset_path: str | None = None,
    dry_run: bool = False,
) -> None:
    repo_root = Path(__file__).parent.parent

    print("=" * 50)
    print("PromptGuard Agent — Weekly Run")
    print("=" * 50)

    # Step 1: Analyze audit log
    print("\n[1/4] Analyzing audit log...")
    report = analyze(audit_path)
    print(report.summary)

    # Step 2: Evaluate against dataset
    eval_result = None
    if dataset_path and Path(dataset_path).exists():
        print(f"\n[2/4] Evaluating against dataset: {dataset_path}")
        eval_result = evaluate(dataset_path=dataset_path, use_node=False)
        kpi = kpi_check(eval_result)
        print(f"  Precision: {eval_result.precision:.4f} {'✅' if kpi['precision_ok'] else '❌'}")
        print(f"  Recall:    {eval_result.recall:.4f} {'✅' if kpi['recall_ok'] else '❌'}")
        print(f"  FP Rate:   {eval_result.fp_rate:.4f} {'✅' if kpi['fp_rate_ok'] else '❌'}")
        print(f"  F1:        {eval_result.f1:.4f}")
    else:
        print("\n[2/4] No dataset provided — skipping evaluation.")

    # Step 3: Generate proposals
    print("\n[3/4] Generating pattern proposals via Claude API...")
    proposals: list[Proposal] = []

    fn_examples = eval_result.fn_examples if eval_result else []
    if fn_examples:
        print(f"  Proposing for {len(fn_examples)} false negatives...")
        try:
            fp_proposals = propose_for_fn(fn_examples[:10])
            proposals.extend(fp_proposals)
        except Exception as e:
            print(f"  ⚠️  FN proposal failed: {e}")

    if report.high_fp_patterns:
        print(f"  Proposing severity adjustments for: {report.high_fp_patterns}")
        fp_stats = [
            {
                "pattern_id": s.pattern_id,
                "tag": s.tag,
                "current_severity": _get_severity(s.pattern_id),
                "fp_rate": s.fp_rate,
            }
            for s in report.pattern_fp_stats
            if s.pattern_id in report.high_fp_patterns
        ]
        fp_texts = [c.prompt for c in report.fp_candidates if c.prompt][:10]
        try:
            adj_proposals = propose_for_fp(fp_stats, fp_texts)
            proposals.extend(adj_proposals)
        except Exception as e:
            print(f"  ⚠️  FP adjustment proposal failed: {e}")

    if not proposals:
        print("  No proposals generated — system looks healthy.")
    else:
        print(f"  Generated {len(proposals)} proposals.")

    # Step 4: Open PR or print report
    print("\n[4/4] Opening PR..." if not dry_run else "\n[4/4] Dry run — printing report.")

    if dry_run or not proposals:
        print("\n" + proposals_to_markdown(proposals))
    else:
        open_pr(repo_root, proposals, report, eval_result)

    print("\n✅ Agent run complete.")


def _get_severity(pattern_id: str) -> float:
    # Approximate severities from patterns.js for PR context
    severities = {
        "P001": 0.95, "P002": 0.95, "P003": 0.90, "P004": 0.85,
        "P005": 0.85, "P006": 0.80, "P007": 0.95, "P008": 0.90,
        "P009": 0.95, "P010": 0.95, "P011": 0.95, "P012": 0.95,
        "P013": 0.80, "P014": 0.75, "P015": 0.90, "P016": 0.90,
        "P017": 0.90, "P018": 0.70, "P019": 0.70, "P020": 0.85,
        "P021": 0.90, "P022": 0.80, "P023": 0.85, "P024": 0.65,
        "P025": 0.85, "P026": 0.60, "P027": 0.85, "P028": 0.90,
        "P029": 0.50, "P030": 0.60, "P031": 0.90, "P032": 0.95,
        "P033": 0.85, "P034": 0.70, "P035": 0.80, "P036": 0.85,
        "P037": 0.75,
    }
    return severities.get(pattern_id, 0.70)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="PromptGuard Agent")
    parser.add_argument("--audit", default="proxy/audit.jsonl", help="Path to audit.jsonl")
    parser.add_argument("--dataset", default=None, help="Path to labeled dataset (CSV/JSONL)")
    parser.add_argument("--dry-run", action="store_true", help="Print proposals without opening PR")
    args = parser.parse_args()

    run(
        audit_path=args.audit,
        dataset_path=args.dataset,
        dry_run=args.dry_run,
    )
